let blocks119str=`{
  "all": [
    {"zh-CN": "金合欢木按钮", "en-US": "Acacia Button"},
    {"zh-CN": "金合欢木门", "en-US": "Acacia Door"},
    {"zh-CN": "金合欢木栅栏", "en-US": "Acacia Fence"},
    {"zh-CN": "金合欢木栅栏门", "en-US": "Acacia Fence Gate"},
    {"zh-CN": "金合欢树叶", "en-US": "Acacia Leaves"},
    {"zh-CN": "金合欢原木", "en-US": "Acacia Log"},
    {"zh-CN": "金合欢木板", "en-US": "Acacia Planks"},
    {"zh-CN": "金合欢木压力板", "en-US": "Acacia Pressure Plate"},
    {"zh-CN": "金合欢树苗", "en-US": "Acacia Sapling"},
    {"zh-CN": "金合欢木告示牌", "en-US": "Acacia Sign"},
    {"zh-CN": "金合欢木台阶", "en-US": "Acacia Slab"},
    {"zh-CN": "金合欢木楼梯", "en-US": "Acacia Stairs"},
    {"zh-CN": "金合欢木活板门", "en-US": "Acacia Trapdoor"},
    {"zh-CN": "金合欢木", "en-US": "Acacia Wood"},
    {"zh-CN": "激活铁轨", "en-US": "Activator Rail"},
    {"zh-CN": "绒球葱", "en-US": "Allium"},
    {"zh-CN": "紫水晶簇", "en-US": "Amethyst Cluster"},
    {"zh-CN": "远古残骸", "en-US": "Ancient Debris"},
    {"zh-CN": "安山岩", "en-US": "Andesite"},
    {"zh-CN": "安山岩台阶", "en-US": "Andesite Slab"},
    {"zh-CN": "安山岩楼梯", "en-US": "Andesite Stairs"},
    {"zh-CN": "安山岩墙", "en-US": "Andesite Wall"},
    {"zh-CN": "铁砧", "en-US": "Anvil"},
    {"zh-CN": "杜鹃花丛", "en-US": "Azalea"},
    {"zh-CN": "杜鹃树叶", "en-US": "Azalea Leaves"},
    {"zh-CN": "蓝花美耳草", "en-US": "Azure Bluet"},
    {"zh-CN": "竹子", "en-US": "Bamboo"},
    {"zh-CN": "竹笋", "en-US": "Bamboo Shoot"},
    {"zh-CN": "木桶", "en-US": "Barrel"},
    {"zh-CN": "屏障", "en-US": "Barrier"},
    {"zh-CN": "玄武岩", "en-US": "Basalt"},
    {"zh-CN": "信标", "en-US": "Beacon"},
    {"zh-CN": "基岩", "en-US": "Bedrock"},
    {"zh-CN": "蜂箱", "en-US": "Bee Nest"},
    {"zh-CN": "蜂巢", "en-US": "Beehive"},
    {"zh-CN": "甜菜", "en-US": "Beetroots"},
    {"zh-CN": "钟", "en-US": "Bell"},
    {"zh-CN": "大型垂滴叶", "en-US": "Big Dripleaf"},
    {"zh-CN": "白桦木按钮", "en-US": "Birch Button"},
    {"zh-CN": "白桦木门", "en-US": "Birch Door"},
    {"zh-CN": "白桦木栅栏", "en-US": "Birch Fence"},
    {"zh-CN": "白桦木栅栏门", "en-US": "Birch Fence Gate"},
    {"zh-CN": "白桦树叶", "en-US": "Birch Leaves"},
    {"zh-CN": "白桦原木", "en-US": "Birch Log"},
    {"zh-CN": "白桦木板", "en-US": "Birch Planks"},
    {"zh-CN": "白桦木压力板", "en-US": "Birch Pressure Plate"},
    {"zh-CN": "白桦树苗", "en-US": "Birch Sapling"},
    {"zh-CN": "白桦木告示牌", "en-US": "Birch Sign"},
    {"zh-CN": "白桦木台阶", "en-US": "Birch Slab"},
    {"zh-CN": "白桦木楼梯", "en-US": "Birch Stairs"},
    {"zh-CN": "白桦木活板门", "en-US": "Birch Trapdoor"},
    {"zh-CN": "白桦木", "en-US": "Birch Wood"},
    {"zh-CN": "黑色旗帜", "en-US": "Black Banner"},
    {"zh-CN": "黑色床", "en-US": "Black Bed"},
    {"zh-CN": "黑色蜡烛", "en-US": "Black Candle"},
    {"zh-CN": "黑色地毯", "en-US": "Black Carpet"},
    {"zh-CN": "黑色混凝土", "en-US": "Black Concrete"},
    {"zh-CN": "黑色混凝土粉末", "en-US": "Black Concrete Powder"},
    {"zh-CN": "黑色带釉陶瓦", "en-US": "Black Glazed Terracotta"},
    {"zh-CN": "黑色潜影盒", "en-US": "Black Shulker Box"},
    {"zh-CN": "黑色染色玻璃", "en-US": "Black Stained Glass"},
    {"zh-CN": "黑色染色玻璃板", "en-US": "Black Stained Glass Pane"},
    {"zh-CN": "黑色陶瓦", "en-US": "Black Terracotta"},
    {"zh-CN": "黑色羊毛", "en-US": "Black Wool"},
    {"zh-CN": "黑石", "en-US": "Blackstone"},
    {"zh-CN": "黑石台阶", "en-US": "Blackstone Slab"},
    {"zh-CN": "黑石楼梯", "en-US": "Blackstone Stairs"},
    {"zh-CN": "黑石墙", "en-US": "Blackstone Wall"},
    {"zh-CN": "高炉", "en-US": "Blast Furnace"},
    {"zh-CN": "紫水晶块", "en-US": "Block of Amethyst"},
    {"zh-CN": "煤炭块", "en-US": "Block of Coal"},
    {"zh-CN": "铜块", "en-US": "Block of Copper"},
    {"zh-CN": "钻石块", "en-US": "Block of Diamond"},
    {"zh-CN": "绿宝石块", "en-US": "Block of Emerald"},
    {"zh-CN": "金块", "en-US": "Block of Gold"},
    {"zh-CN": "铁块", "en-US": "Block of Iron"},
    {"zh-CN": "青金石块", "en-US": "Block of Lapis Lazuli"},
    {"zh-CN": "下界合金块", "en-US": "Block of Netherite"},
    {"zh-CN": "石英块", "en-US": "Block of Quartz"},
    {"zh-CN": "粗铜块", "en-US": "Block of Raw Copper"},
    {"zh-CN": "粗金块", "en-US": "Block of Raw Gold"},
    {"zh-CN": "粗铁块", "en-US": "Block of Raw Iron"},
    {"zh-CN": "红石块", "en-US": "Block of Redstone"},
    {"zh-CN": "蓝色旗帜", "en-US": "Blue Banner"},
    {"zh-CN": "蓝色床", "en-US": "Blue Bed"},
    {"zh-CN": "蓝色蜡烛", "en-US": "Blue Candle"},
    {"zh-CN": "蓝色地毯", "en-US": "Blue Carpet"},
    {"zh-CN": "蓝色混凝土", "en-US": "Blue Concrete"},
    {"zh-CN": "蓝色混凝土粉末", "en-US": "Blue Concrete Powder"},
    {"zh-CN": "蓝色带釉陶瓦", "en-US": "Blue Glazed Terracotta"},
    {"zh-CN": "蓝冰", "en-US": "Blue Ice"},
    {"zh-CN": "兰花", "en-US": "Blue Orchid"},
    {"zh-CN": "蓝色潜影盒", "en-US": "Blue Shulker Box"},
    {"zh-CN": "蓝色染色玻璃", "en-US": "Blue Stained Glass"},
    {"zh-CN": "蓝色染色玻璃板", "en-US": "Blue Stained Glass Pane"},
    {"zh-CN": "蓝色陶瓦", "en-US": "Blue Terracotta"},
    {"zh-CN": "蓝色羊毛", "en-US": "Blue Wool"},
    {"zh-CN": "骨块", "en-US": "Bone Block"},
    {"zh-CN": "书架", "en-US": "Bookshelf"},
    {"zh-CN": "脑纹珊瑚", "en-US": "Brain Coral"},
    {"zh-CN": "脑纹珊瑚块", "en-US": "Brain Coral Block"},
    {"zh-CN": "脑纹珊瑚扇", "en-US": "Brain Coral Fan"},
    {"zh-CN": "酿造台", "en-US": "Brewing Stand"},
    {"zh-CN": "砖块台阶", "en-US": "Brick Slab"},
    {"zh-CN": "砖块楼梯", "en-US": "Brick Stairs"},
    {"zh-CN": "砖块墙", "en-US": "Brick Wall"},
    {"zh-CN": "砖块", "en-US": "Bricks"},
    {"zh-CN": "棕色旗帜", "en-US": "Brown Banner"},
    {"zh-CN": "棕色床", "en-US": "Brown Bed"},
    {"zh-CN": "棕色蜡烛", "en-US": "Brown Candle"},
    {"zh-CN": "棕色地毯", "en-US": "Brown Carpet"},
    {"zh-CN": "棕色混凝土", "en-US": "Brown Concrete"},
    {"zh-CN": "棕色混凝土粉末", "en-US": "Brown Concrete Powder"},
    {"zh-CN": "棕色带釉陶瓦", "en-US": "Brown Glazed Terracotta"},
    {"zh-CN": "棕色蘑菇", "en-US": "Brown Mushroom"},
    {"zh-CN": "棕色蘑菇方块", "en-US": "Brown Mushroom Block"},
    {"zh-CN": "棕色潜影盒", "en-US": "Brown Shulker Box"},
    {"zh-CN": "棕色染色玻璃", "en-US": "Brown Stained Glass"},
    {"zh-CN": "棕色染色玻璃板", "en-US": "Brown Stained Glass Pane"},
    {"zh-CN": "棕色陶瓦", "en-US": "Brown Terracotta"},
    {"zh-CN": "棕色羊毛", "en-US": "Brown Wool"},
    {"zh-CN": "气泡珊瑚", "en-US": "Bubble Coral"},
    {"zh-CN": "气泡珊瑚块", "en-US": "Bubble Coral Block"},
    {"zh-CN": "气泡珊瑚扇", "en-US": "Bubble Coral Fan"},
    {"zh-CN": "紫水晶母岩", "en-US": "Budding Amethyst"},
    {"zh-CN": "仙人掌", "en-US": "Cactus"},
    {"zh-CN": "蛋糕", "en-US": "Cake"},
    {"zh-CN": "方解石", "en-US": "Calcite"},
    {"zh-CN": "营火", "en-US": "Campfire"},
    {"zh-CN": "蜡烛", "en-US": "Candle"},
    {"zh-CN": "胡萝卜", "en-US": "Carrots"},
    {"zh-CN": "制图台", "en-US": "Cartography Table"},
    {"zh-CN": "雕刻过的南瓜", "en-US": "Carved Pumpkin"},
    {"zh-CN": "炼药锅", "en-US": "Cauldron"},
    {"zh-CN": "洞穴藤蔓", "en-US": "Cave Vines"},
    {"zh-CN": "锁链", "en-US": "Chain"},
    {"zh-CN": "连锁型命令方块", "en-US": "Chain Command Block"},
    {"zh-CN": "箱子", "en-US": "Chest"},
    {"zh-CN": "开裂的铁砧", "en-US": "Chipped Anvil"},
    {"zh-CN": "錾制深板岩", "en-US": "Chiseled Deepslate"},
    {"zh-CN": "錾制下界砖块", "en-US": "Chiseled Nether Bricks"},
    {"zh-CN": "錾制磨制黑石", "en-US": "Chiseled Polished Blackstone"},
    {"zh-CN": "錾制石英块", "en-US": "Chiseled Quartz Block"},
    {"zh-CN": "錾制红砂岩", "en-US": "Chiseled Red Sandstone"},
    {"zh-CN": "錾制砂岩", "en-US": "Chiseled Sandstone"},
    {"zh-CN": "錾制石砖", "en-US": "Chiseled Stone Bricks"},
    {"zh-CN": "紫颂果", "en-US": "Chorus Flower"},
    {"zh-CN": "紫颂植株", "en-US": "Chorus Plant"},
    {"zh-CN": "黏土块", "en-US": "Clay"},
    {"zh-CN": "煤矿石", "en-US": "Coal Ore"},
    {"zh-CN": "砂土", "en-US": "Coarse Dirt"},
    {"zh-CN": "深板岩圆石", "en-US": "Cobbled Deepslate"},
    {"zh-CN": "深板岩圆石台阶", "en-US": "Cobbled Deepslate Slab"},
    {"zh-CN": "深板岩圆石楼梯", "en-US": "Cobbled Deepslate Stairs"},
    {"zh-CN": "深板岩圆石墙", "en-US": "Cobbled Deepslate Wall"},
    {"zh-CN": "圆石", "en-US": "Cobblestone"},
    {"zh-CN": "圆石台阶", "en-US": "Cobblestone Slab"},
    {"zh-CN": "圆石楼梯", "en-US": "Cobblestone Stairs"},
    {"zh-CN": "圆石墙", "en-US": "Cobblestone Wall"},
    {"zh-CN": "蜘蛛网", "en-US": "Cobweb"},
    {"zh-CN": "可可果", "en-US": "Cocoa"},
    {"zh-CN": "命令方块", "en-US": "Command Block"},
    {"zh-CN": "堆肥桶", "en-US": "Composter"},
    {"zh-CN": "潮涌核心", "en-US": "Conduit"},
    {"zh-CN": "铜矿石", "en-US": "Copper Ore"},
    {"zh-CN": "矢车菊", "en-US": "Cornflower"},
    {"zh-CN": "裂纹深板岩砖", "en-US": "Cracked Deepslate Bricks"},
    {"zh-CN": "裂纹深板岩瓦", "en-US": "Cracked Deepslate Tiles"},
    {"zh-CN": "裂纹磨制黑石砖", "en-US": "Cracked Polished Blackstone Bricks"},
    {"zh-CN": "裂纹下界砖块", "en-US": "Cracked Nether Bricks"},
    {"zh-CN": "裂纹石砖", "en-US": "Cracked Stone Bricks"},
    {"zh-CN": "工作台", "en-US": "Crafting Table"},
    {"zh-CN": "苦力怕的头", "en-US": "Creeper Head"},
    {"zh-CN": "绯红木按钮", "en-US": "Crimson Button"},
    {"zh-CN": "绯红木门", "en-US": "Crimson Door"},
    {"zh-CN": "绯红木栅栏", "en-US": "Crimson Fence"},
    {"zh-CN": "绯红木栅栏门", "en-US": "Crimson Fence Gate"},
    {"zh-CN": "绯红菌", "en-US": "Crimson Fungus"},
    {"zh-CN": "绯红菌核", "en-US": "Crimson Hyphae"},
    {"zh-CN": "绯红菌岩", "en-US": "Crimson Nylium"},
    {"zh-CN": "绯红木板", "en-US": "Crimson Planks"},
    {"zh-CN": "绯红木压力板", "en-US": "Crimson Pressure Plate"},
    {"zh-CN": "绯红菌索", "en-US": "Crimson Roots"},
    {"zh-CN": "绯红木告示牌", "en-US": "Crimson Sign"},
    {"zh-CN": "绯红木台阶", "en-US": "Crimson Slab"},
    {"zh-CN": "绯红木楼梯", "en-US": "Crimson Stairs"},
    {"zh-CN": "绯红菌柄", "en-US": "Crimson Stem"},
    {"zh-CN": "绯红木活板门", "en-US": "Crimson Trapdoor"},
    {"zh-CN": "哭泣的黑曜石", "en-US": "Crying Obsidian"},
    {"zh-CN": "切制铜块", "en-US": "Cut Copper"},
    {"zh-CN": "切制铜台阶", "en-US": "Cut Copper Slab"},
    {"zh-CN": "切制铜楼梯", "en-US": "Cut Copper Stairs"},
    {"zh-CN": "切制红砂岩", "en-US": "Cut Red Sandstone"},
    {"zh-CN": "切制红砂岩台阶", "en-US": "Cut Red Sandstone Slab"},
    {"zh-CN": "切制砂岩", "en-US": "Cut Sandstone"},
    {"zh-CN": "切制砂岩台阶", "en-US": "Cut Sandstone Slab"},
    {"zh-CN": "青色旗帜", "en-US": "Cyan Banner"},
    {"zh-CN": "青色床", "en-US": "Cyan Bed"},
    {"zh-CN": "青色蜡烛", "en-US": "Cyan Candle"},
    {"zh-CN": "青色地毯", "en-US": "Cyan Carpet"},
    {"zh-CN": "青色混凝土", "en-US": "Cyan Concrete"},
    {"zh-CN": "青色混凝土粉末", "en-US": "Cyan Concrete Powder"},
    {"zh-CN": "青色带釉陶瓦", "en-US": "Cyan Glazed Terracotta"},
    {"zh-CN": "青色潜影盒", "en-US": "Cyan Shulker Box"},
    {"zh-CN": "青色染色玻璃", "en-US": "Cyan Stained Glass"},
    {"zh-CN": "青色染色玻璃板", "en-US": "Cyan Stained Glass Pane"},
    {"zh-CN": "青色陶瓦", "en-US": "Cyan Terracotta"},
    {"zh-CN": "青色羊毛", "en-US": "Cyan Wool"},
    {"zh-CN": "损坏的铁砧", "en-US": "Damaged Anvil"},
    {"zh-CN": "蒲公英", "en-US": "Dandelion"},
    {"zh-CN": "深色橡木按钮", "en-US": "Dark Oak Button"},
    {"zh-CN": "深色橡木门", "en-US": "Dark Oak Door"},
    {"zh-CN": "深色橡木栅栏", "en-US": "Dark Oak Fence"},
    {"zh-CN": "深色橡木栅栏门", "en-US": "Dark Oak Fence Gate"},
    {"zh-CN": "深色橡树树叶", "en-US": "Dark Oak Leaves"},
    {"zh-CN": "深色橡木原木", "en-US": "Dark Oak Log"},
    {"zh-CN": "深色橡木木板", "en-US": "Dark Oak Planks"},
    {"zh-CN": "深色橡木压力板", "en-US": "Dark Oak Pressure Plate"},
    {"zh-CN": "深色橡树树苗", "en-US": "Dark Oak Sapling"},
    {"zh-CN": "深色橡木告示牌", "en-US": "Dark Oak Sign"},
    {"zh-CN": "深色橡木台阶", "en-US": "Dark Oak Slab"},
    {"zh-CN": "深色橡木楼梯", "en-US": "Dark Oak Stairs"},
    {"zh-CN": "深色橡木活板门", "en-US": "Dark Oak Trapdoor"},
    {"zh-CN": "深色橡木", "en-US": "Dark Oak Wood"},
    {"zh-CN": "暗海晶石", "en-US": "Dark Prismarine"},
    {"zh-CN": "暗海晶石台阶", "en-US": "Dark Prismarine Slab"},
    {"zh-CN": "暗海晶石楼梯", "en-US": "Dark Prismarine Stairs"},
    {"zh-CN": "阳光探测器", "en-US": "Daylight Detector"},
    {"zh-CN": "失活的脑纹珊瑚", "en-US": "Dead Brain Coral"},
    {"zh-CN": "失活的脑纹珊瑚块", "en-US": "Dead Brain Coral Block"},
    {"zh-CN": "失活的脑纹珊瑚扇", "en-US": "Dead Brain Coral Fan"},
    {"zh-CN": "失活的气泡珊瑚", "en-US": "Dead Bubble Coral"},
    {"zh-CN": "失活的气泡珊瑚块", "en-US": "Dead Bubble Coral Block"},
    {"zh-CN": "失活的气泡珊瑚扇", "en-US": "Dead Bubble Coral Fan"},
    {"zh-CN": "枯萎的灌木", "en-US": "Dead Bush"},
    {"zh-CN": "失活的火珊瑚", "en-US": "Dead Fire Coral"},
    {"zh-CN": "失活的火珊瑚块", "en-US": "Dead Fire Coral Block"},
    {"zh-CN": "失活的火珊瑚扇", "en-US": "Dead Fire Coral Fan"},
    {"zh-CN": "失活的鹿角珊瑚", "en-US": "Dead Horn Coral"},
    {"zh-CN": "失活的鹿角珊瑚块", "en-US": "Dead Horn Coral Block"},
    {"zh-CN": "失活的鹿角珊瑚扇", "en-US": "Dead Horn Coral Fan"},
    {"zh-CN": "失活的管珊瑚", "en-US": "Dead Tube Coral"},
    {"zh-CN": "失活的管珊瑚块", "en-US": "Dead Tube Coral Block"},
    {"zh-CN": "失活的管珊瑚扇", "en-US": "Dead Tube Coral Fan"},
    {"zh-CN": "深板岩", "en-US": "Deepslate"},
    {"zh-CN": "深板岩砖", "en-US": "Deepslate Bricks"},
    {"zh-CN": "深板岩砖台阶", "en-US": "Deepslate Brick Slab"},
    {"zh-CN": "深板岩砖楼梯", "en-US": "Deepslate Brick Stairs"},
    {"zh-CN": "深板岩砖墙", "en-US": "Deepslate Brick Wall"},
    {"zh-CN": "深层煤矿石", "en-US": "Deepslate Coal Ore"},
    {"zh-CN": "深层铜矿石", "en-US": "Deepslate Copper Ore"},
    {"zh-CN": "深层钻石矿石", "en-US": "Deepslate Diamond Ore"},
    {"zh-CN": "深层绿宝石矿石", "en-US": "Deepslate Emerald Ore"},
    {"zh-CN": "深层金矿石", "en-US": "Deepslate Gold Ore"},
    {"zh-CN": "深层铁矿石", "en-US": "Deepslate Iron Ore"},
    {"zh-CN": "深层青金石矿石", "en-US": "Deepslate Lapis Lazuli Ore"},
    {"zh-CN": "深层红石矿石", "en-US": "Deepslate Redstone Ore"},
    {"zh-CN": "深板岩瓦", "en-US": "Deepslate Tiles"},
    {"zh-CN": "深板岩瓦台阶", "en-US": "Deepslate Tile Slab"},
    {"zh-CN": "深板岩瓦楼梯", "en-US": "Deepslate Tile Stairs"},
    {"zh-CN": "深板岩瓦墙", "en-US": "Deepslate Tile Wall"},
    {"zh-CN": "探测铁轨", "en-US": "Detector Rail"},
    {"zh-CN": "钻石矿石", "en-US": "Diamond Ore"},
    {"zh-CN": "闪长岩", "en-US": "Diorite"},
    {"zh-CN": "闪长岩台阶", "en-US": "Diorite Slab"},
    {"zh-CN": "闪长岩楼梯", "en-US": "Diorite Stairs"},
    {"zh-CN": "闪长岩墙", "en-US": "Diorite Wall"},
    {"zh-CN": "泥土", "en-US": "Dirt"},
    {"zh-CN": "发射器", "en-US": "Dispenser"},
    {"zh-CN": "龙蛋", "en-US": "Dragon Egg"},
    {"zh-CN": "龙首", "en-US": "Dragon Head"},
    {"zh-CN": "干海带块", "en-US": "Dried Kelp Block"},
    {"zh-CN": "滴水石块", "en-US": "Dripstone Block"},
    {"zh-CN": "投掷器", "en-US": "Dropper"},
    {"zh-CN": "绿宝石矿石", "en-US": "Emerald Ore"},
    {"zh-CN": "附魔台", "en-US": "Enchanting Table"},
    {"zh-CN": "末地传送门框架", "en-US": "End Portal Frame"},
    {"zh-CN": "末地烛", "en-US": "End Rod"},
    {"zh-CN": "末地石", "en-US": "End Stone"},
    {"zh-CN": "末地石砖台阶", "en-US": "End Stone Brick Slab"},
    {"zh-CN": "末地石砖楼梯", "en-US": "End Stone Brick Stairs"},
    {"zh-CN": "末地石砖墙", "en-US": "End Stone Brick Wall"},
    {"zh-CN": "末地石砖", "en-US": "End Stone Bricks"},
    {"zh-CN": "末影箱", "en-US": "Ender Chest"},
    {"zh-CN": "斑驳的铜块", "en-US": "Exposed Copper"},
    {"zh-CN": "斑驳的切制铜块", "en-US": "Exposed Cut Copper"},
    {"zh-CN": "斑驳的切制铜台阶", "en-US": "Exposed Cut Copper Slab"},
    {"zh-CN": "斑驳的切制铜楼梯", "en-US": "Exposed Cut Copper Stairs"},
    {"zh-CN": "耕地", "en-US": "Farmland"},
    {"zh-CN": "蕨", "en-US": "Fern"},
    {"zh-CN": "火", "en-US": "Fire"},
    {"zh-CN": "火珊瑚", "en-US": "Fire Coral"},
    {"zh-CN": "火珊瑚块", "en-US": "Fire Coral Block"},
    {"zh-CN": "火珊瑚扇", "en-US": "Fire Coral Fan"},
    {"zh-CN": "制箭台", "en-US": "Fletching Table"},
    {"zh-CN": "花盆", "en-US": "Flower Pot"},
    {"zh-CN": "盛开的杜鹃花丛", "en-US": "Flowering Azalea"},
    {"zh-CN": "盛开的杜鹃树叶", "en-US": "Flowering Azalea Leaves"},
    {"zh-CN": "青蛙卵", "en-US": "Frogspawn"},
    {"zh-CN": "熔炉", "en-US": "Furnace"},
    {"zh-CN": "镶金黑石", "en-US": "Gilded Blackstone"},
    {"zh-CN": "玻璃", "en-US": "Glass"},
    {"zh-CN": "玻璃板", "en-US": "Glass Pane"},
    {"zh-CN": "荧石", "en-US": "Glowstone"},
    {"zh-CN": "发光地衣", "en-US": "Glow Lichen"},
    {"zh-CN": "金矿石", "en-US": "Gold Ore"},
    {"zh-CN": "花岗岩", "en-US": "Granite"},
    {"zh-CN": "花岗岩台阶", "en-US": "Granite Slab"},
    {"zh-CN": "花岗岩楼梯", "en-US": "Granite Stairs"},
    {"zh-CN": "花岗岩墙", "en-US": "Granite Wall"},
    {"zh-CN": "草丛", "en-US": "Grass"},
    {"zh-CN": "草方块", "en-US": "Grass Block"},
    {"zh-CN": "土径", "en-US": "Gravel"},
    {"zh-CN": "灰色旗帜", "en-US": "Gray Banner"},
    {"zh-CN": "灰色床", "en-US": "Gray Bed"},
    {"zh-CN": "灰色蜡烛", "en-US": "Gray Candle"},
    {"zh-CN": "灰色地毯", "en-US": "Gray Carpet"},
    {"zh-CN": "灰色混凝土", "en-US": "Gray Concrete"},
    {"zh-CN": "灰色混凝土粉末", "en-US": "Gray Concrete Powder"},
    {"zh-CN": "灰色带釉陶瓦", "en-US": "Gray Glazed Terracotta"},
    {"zh-CN": "灰色潜影盒", "en-US": "Gray Shulker Box"},
    {"zh-CN": "灰色染色玻璃", "en-US": "Gray Stained Glass"},
    {"zh-CN": "灰色染色玻璃板", "en-US": "Gray Stained Glass Pane"},
    {"zh-CN": "灰色陶瓦", "en-US": "Gray Terracotta"},
    {"zh-CN": "灰色羊毛", "en-US": "Gray Wool"},
    {"zh-CN": "绿色旗帜", "en-US": "Green Banner"},
    {"zh-CN": "绿色床", "en-US": "Green Bed"},
    {"zh-CN": "绿色蜡烛", "en-US": "Green Candle"},
    {"zh-CN": "绿色地毯", "en-US": "Green Carpet"},
    {"zh-CN": "绿色混凝土", "en-US": "Green Concrete"},
    {"zh-CN": "绿色混凝土粉末", "en-US": "Green Concrete Powder"},
    {"zh-CN": "绿色带釉陶瓦", "en-US": "Green Glazed Terracotta"},
    {"zh-CN": "绿色潜影盒", "en-US": "Green Shulker Box"},
    {"zh-CN": "绿色染色玻璃", "en-US": "Green Stained Glass"},
    {"zh-CN": "绿色染色玻璃板", "en-US": "Green Stained Glass Pane"},
    {"zh-CN": "绿色陶瓦", "en-US": "Green Terracotta"},
    {"zh-CN": "绿色羊毛", "en-US": "Green Wool"},
    {"zh-CN": "砂轮", "en-US": "Grindstone"},
    {"zh-CN": "干草块", "en-US": "Hanging Roots"},
    {"zh-CN": "重质测重压力板", "en-US": "Heavy Weighted Pressure Plate"},
    {"zh-CN": "蜂蜜块", "en-US": "Honey Block"},
    {"zh-CN": "蜜脾块", "en-US": "Honeycomb Block"},
    {"zh-CN": "漏斗", "en-US": "Hopper"},
    {"zh-CN": "鹿角珊瑚", "en-US": "Horn Coral"},
    {"zh-CN": "鹿角珊瑚块", "en-US": "Horn Coral Block"},
    {"zh-CN": "鹿角珊瑚扇", "en-US": "Horn Coral Fan"},
    {"zh-CN": "冰", "en-US": "Ice"},
    {"zh-CN": "被虫蚀的錾制石砖", "en-US": "Infested Chiseled Stone Bricks"},
    {"zh-CN": "被虫蚀的圆石", "en-US": "Infested Cobblestone"},
    {"zh-CN": "被虫蚀的裂纹石砖", "en-US": "Infested Cracked Stone Bricks"},
    {"zh-CN": "被虫蚀的深板岩", "en-US": "Infested Deepslate"},
    {"zh-CN": "被虫蚀的苔石砖", "en-US": "Infested Mossy Stone Bricks"},
    {"zh-CN": "被虫蚀的石头", "en-US": "Infested Stone"},
    {"zh-CN": "被虫蚀的石砖", "en-US": "Infested Stone Bricks"},
    {"zh-CN": "铁栏杆", "en-US": "Iron Bars"},
    {"zh-CN": "铁门", "en-US": "Iron Door"},
    {"zh-CN": "铁矿石", "en-US": "Iron Ore"},
    {"zh-CN": "铁活板门", "en-US": "Iron Trapdoor"},
    {"zh-CN": "南瓜灯", "en-US": "Jack o'Lantern"},
    {"zh-CN": "拼图方块", "en-US": "Jigsaw Block"},
    {"zh-CN": "唱片机", "en-US": "Jukebox"},
    {"zh-CN": "丛林木按钮", "en-US": "Jungle Button"},
    {"zh-CN": "丛林木门", "en-US": "Jungle Door"},
    {"zh-CN": "丛林木栅栏", "en-US": "Jungle Fence"},
    {"zh-CN": "丛林木栅栏门", "en-US": "Jungle Fence Gate"},
    {"zh-CN": "丛林树叶", "en-US": "Jungle Leaves"},
    {"zh-CN": "丛林原木", "en-US": "Jungle Log"},
    {"zh-CN": "丛林木板", "en-US": "Jungle Planks"},
    {"zh-CN": "丛林木压力板", "en-US": "Jungle Pressure Plate"},
    {"zh-CN": "丛林树苗", "en-US": "Jungle Sapling"},
    {"zh-CN": "丛林木告示牌", "en-US": "Jungle Sign"},
    {"zh-CN": "丛林木台阶", "en-US": "Jungle Slab"},
    {"zh-CN": "丛林木楼梯", "en-US": "Jungle Stairs"},
    {"zh-CN": "丛林木活板门", "en-US": "Jungle Trapdoor"},
    {"zh-CN": "丛林木", "en-US": "Jungle Wood"},
    {"zh-CN": "海带", "en-US": "Kelp"},
    {"zh-CN": "梯子", "en-US": "Ladder"},
    {"zh-CN": "灯笼", "en-US": "Lantern"},
    {"zh-CN": "青金石矿石", "en-US": "Lapis Lazuli Ore"},
    {"zh-CN": "大型紫晶芽", "en-US": "Large Amethyst Bud"},
    {"zh-CN": "大型蕨", "en-US": "Large Fern"},
    {"zh-CN": "熔岩", "en-US": "Lava"},
    {"zh-CN": "讲台", "en-US": "Lectern"},
    {"zh-CN": "拉杆", "en-US": "Lever"},
    {"zh-CN": "光源方块", "en-US": "Light Block"},
    {"zh-CN": "淡蓝色旗帜", "en-US": "Light Blue Banner"},
    {"zh-CN": "淡蓝色床", "en-US": "Light Blue Bed"},
    {"zh-CN": "淡蓝色蜡烛", "en-US": "Light Blue Candle"},
    {"zh-CN": "淡蓝色地毯", "en-US": "Light Blue Carpet"},
    {"zh-CN": "淡蓝色混凝土", "en-US": "Light Blue Concrete"},
    {"zh-CN": "淡蓝色混凝土粉末", "en-US": "Light Blue Concrete Powder"},
    {"zh-CN": "淡蓝色带釉陶瓦", "en-US": "Light Blue Glazed Terracotta"},
    {"zh-CN": "淡蓝色潜影盒", "en-US": "Light Blue Shulker Box"},
    {"zh-CN": "淡蓝色染色玻璃", "en-US": "Light Blue Stained Glass"},
    {"zh-CN": "淡蓝色染色玻璃板", "en-US": "Light Blue Stained Glass Pane"},
    {"zh-CN": "淡蓝色陶瓦", "en-US": "Light Blue Terracotta"},
    {"zh-CN": "淡蓝色羊毛", "en-US": "Light Blue Wool"},
    {"zh-CN": "淡灰色旗帜", "en-US": "Light Gray Banner"},
    {"zh-CN": "淡灰色床", "en-US": "Light Gray Bed"},
    {"zh-CN": "淡灰色蜡烛", "en-US": "Light Gray Candle"},
    {"zh-CN": "淡灰色地毯", "en-US": "Light Gray Carpet"},
    {"zh-CN": "淡灰色混凝土", "en-US": "Light Gray Concrete"},
    {"zh-CN": "淡灰色混凝土粉末", "en-US": "Light Gray Concrete Powder"},
    {"zh-CN": "淡灰色带釉陶瓦", "en-US": "Light Gray Glazed Terracotta"},
    {"zh-CN": "淡灰色潜影盒", "en-US": "Light Gray Shulker Box"},
    {"zh-CN": "淡灰色染色玻璃", "en-US": "Light Gray Stained Glass"},
    {"zh-CN": "淡灰色染色玻璃板", "en-US": "Light Gray Stained Glass Pane"},
    {"zh-CN": "淡灰色陶瓦", "en-US": "Light Gray Terracotta"},
    {"zh-CN": "淡灰色羊毛", "en-US": "Light Gray Wool"},
    {"zh-CN": "轻质测重压力板", "en-US": "Light Weighted Pressure Plate"},
    {"zh-CN": "避雷针", "en-US": "Lightning Rod"},
    {"zh-CN": "丁香", "en-US": "Lilac"},
    {"zh-CN": "睡莲", "en-US": "Lily of the Valley"},
    {"zh-CN": "铃兰", "en-US": "Lily Pad"},
    {"zh-CN": "黄绿色旗帜", "en-US": "Lime Banner"},
    {"zh-CN": "黄绿色床", "en-US": "Lime Bed"},
    {"zh-CN": "黄绿色蜡烛", "en-US": "Lime Candle"},
    {"zh-CN": "黄绿色地毯", "en-US": "Lime Carpet"},
    {"zh-CN": "黄绿色混凝土", "en-US": "Lime Concrete"},
    {"zh-CN": "黄绿色混凝土粉末", "en-US": "Lime Concrete Powder"},
    {"zh-CN": "黄绿色带釉陶瓦", "en-US": "Lime Glazed Terracotta"},
    {"zh-CN": "黄绿色潜影盒", "en-US": "Lime Shulker Box"},
    {"zh-CN": "黄绿色染色玻璃", "en-US": "Lime Stained Glass"},
    {"zh-CN": "黄绿色染色玻璃板", "en-US": "Lime Stained Glass Pane"},
    {"zh-CN": "黄绿色陶瓦", "en-US": "Lime Terracotta"},
    {"zh-CN": "黄绿色羊毛", "en-US": "Lime Wool"},
    {"zh-CN": "磁石", "en-US": "Lodestone"},
    {"zh-CN": "织布机", "en-US": "Loom"},
    {"zh-CN": "品红色旗帜", "en-US": "Magenta Banner"},
    {"zh-CN": "品红色床", "en-US": "Magenta Bed"},
    {"zh-CN": "品红色蜡烛", "en-US": "Magenta Candle"},
    {"zh-CN": "品红色地毯", "en-US": "Magenta Carpet"},
    {"zh-CN": "品红色混凝土", "en-US": "Magenta Concrete"},
    {"zh-CN": "品红色混凝土粉末", "en-US": "Magenta Concrete Powder"},
    {"zh-CN": "品红色带釉陶瓦", "en-US": "Magenta Glazed Terracotta"},
    {"zh-CN": "品红色潜影盒", "en-US": "Magenta Shulker Box"},
    {"zh-CN": "品红色染色玻璃", "en-US": "Magenta Stained Glass"},
    {"zh-CN": "品红色染色玻璃板", "en-US": "Magenta Stained Glass Pane"},
    {"zh-CN": "品红色陶瓦", "en-US": "Magenta Terracotta"},
    {"zh-CN": "品红色羊毛", "en-US": "Magenta Wool"},
    {"zh-CN": "岩浆块", "en-US": "Magma Block"},
    {"zh-CN": "红树木按钮", "en-US": "Mangrove Button"},
    {"zh-CN": "红树木门", "en-US": "Mangrove Door"},
    {"zh-CN": "红树木栅栏", "en-US": "Mangrove Fence"},
    {"zh-CN": "红树木栅栏门", "en-US": "Mangrove Fence Gate"},
    {"zh-CN": "红树树叶", "en-US": "Mangrove Leaves"},
    {"zh-CN": "红树原木", "en-US": "Mangrove Log"},
    {"zh-CN": "红树木压力板", "en-US": "Mangrove Pressure Plate"},
    {"zh-CN": "红树胎生苗", "en-US": "Mangrove Propagule"},
    {"zh-CN": "红树木板", "en-US": "Mangrove Planks"},
    {"zh-CN": "红树根", "en-US": "Mangrove Roots"},
    {"zh-CN": "红树木告示牌", "en-US": "Mangrove Sign"},
    {"zh-CN": "红树木台阶", "en-US": "Mangrove Slab"},
    {"zh-CN": "红树木楼梯", "en-US": "Mangrove Stairs"},
    {"zh-CN": "红树木活板门", "en-US": "Mangrove Trapdoor"},
    {"zh-CN": "红树木", "en-US": "Mangrove Wood"},
    {"zh-CN": "中型紫晶芽", "en-US": "Medium Amethyst Bud"},
    {"zh-CN": "西瓜", "en-US": "Melon"},
    {"zh-CN": "西瓜茎", "en-US": "Melon Stem"},
    {"zh-CN": "苔石", "en-US": "Moss Block"},
    {"zh-CN": "苔石台阶", "en-US": "Moss Carpet"},
    {"zh-CN": "苔石楼梯", "en-US": "Mossy Cobblestone"},
    {"zh-CN": "苔石墙", "en-US": "Mossy Cobblestone Slab"},
    {"zh-CN": "苔石砖台阶", "en-US": "Mossy Cobblestone Stairs"},
    {"zh-CN": "苔石砖楼梯", "en-US": "Mossy Cobblestone Wall"},
    {"zh-CN": "苔石砖墙", "en-US": "Mossy Stone Brick Slab"},
    {"zh-CN": "苔石砖", "en-US": "Mossy Stone Brick Stairs"},
    {"zh-CN": "泥巴", "en-US": "Mud"},
    {"zh-CN": "泥砖台阶", "en-US": "Mud Brick Slab"},
    {"zh-CN": "泥砖楼梯", "en-US": "Mud Brick Stairs"},
    {"zh-CN": "泥砖墙", "en-US": "Mud Brick Wall"},
    {"zh-CN": "泥砖", "en-US": "Mud Bricks"},
    {"zh-CN": "沾泥的红树根", "en-US": "Muddy Mangrove Roots"},
    {"zh-CN": "蘑菇柄", "en-US": "Mushroom Stem"},
    {"zh-CN": "菌丝", "en-US": "Mycelium"},
    {"zh-CN": "下界砖栅栏", "en-US": "Nether Brick Fence"},
    {"zh-CN": "下界砖台阶", "en-US": "Nether Brick Slab"},
    {"zh-CN": "下界砖楼梯", "en-US": "Nether Brick Stairs"},
    {"zh-CN": "下界砖墙", "en-US": "Nether Brick Wall"},
    {"zh-CN": "下界砖块", "en-US": "Nether Bricks"},
    {"zh-CN": "下界金矿石", "en-US": "Nether Gold Ore"},
    {"zh-CN": "下界石英矿石", "en-US": "Nether Quartz Ore"},
    {"zh-CN": "下界苗", "en-US": "Nether Sprouts"},
    {"zh-CN": "下界疣", "en-US": "Nether Wart"},
    {"zh-CN": "下界疣块", "en-US": "Nether Wart Block"},
    {"zh-CN": "下界岩", "en-US": "Netherrack"},
    {"zh-CN": "音符盒", "en-US": "Note Block"},
    {"zh-CN": "橡木按钮", "en-US": "Oak Button"},
    {"zh-CN": "橡木门", "en-US": "Oak Door"},
    {"zh-CN": "橡木栅栏", "en-US": "Oak Fence"},
    {"zh-CN": "橡木栅栏门", "en-US": "Oak Fence Gate"},
    {"zh-CN": "橡树树叶", "en-US": "Oak Leaves"},
    {"zh-CN": "橡木原木", "en-US": "Oak Log"},
    {"zh-CN": "橡木木板", "en-US": "Oak Planks"},
    {"zh-CN": "橡木压力板", "en-US": "Oak Pressure Plate"},
    {"zh-CN": "橡树树苗", "en-US": "Oak Sapling"},
    {"zh-CN": "橡木告示牌", "en-US": "Oak Sign"},
    {"zh-CN": "橡木台阶", "en-US": "Oak Slab"},
    {"zh-CN": "橡木楼梯", "en-US": "Oak Stairs"},
    {"zh-CN": "橡木活板门", "en-US": "Oak Trapdoor"},
    {"zh-CN": "橡木", "en-US": "Oak Wood"},
    {"zh-CN": "侦测器", "en-US": "Observer"},
    {"zh-CN": "黑曜石", "en-US": "Obsidian"},
    {"zh-CN": "赭黄蛙明灯", "en-US": "Ochre Froglight"},
    {"zh-CN": "灾厄旗帜", "en-US": "Ominous Banner"},
    {"zh-CN": "橙色旗帜", "en-US": "Orange Banner"},
    {"zh-CN": "橙色床", "en-US": "Orange Bed"},
    {"zh-CN": "橙色蜡烛", "en-US": "Orange Candle"},
    {"zh-CN": "橙色地毯", "en-US": "Orange Carpet"},
    {"zh-CN": "橙色混凝土", "en-US": "Orange Concrete"},
    {"zh-CN": "橙色混凝土粉末", "en-US": "Orange Concrete Powder"},
    {"zh-CN": "橙色带釉陶瓦", "en-US": "Orange Glazed Terracotta"},
    {"zh-CN": "橙色潜影盒", "en-US": "Orange Shulker Box"},
    {"zh-CN": "橙色染色玻璃", "en-US": "Orange Stained Glass"},
    {"zh-CN": "橙色染色玻璃板", "en-US": "Orange Stained Glass Pane"},
    {"zh-CN": "橙色陶瓦", "en-US": "Orange Terracotta"},
    {"zh-CN": "橙色郁金香", "en-US": "Orange Tulip"},
    {"zh-CN": "橙色羊毛", "en-US": "Orange Wool"},
    {"zh-CN": "滨菊", "en-US": "Oxeye Daisy"},
    {"zh-CN": "氧化的铜块", "en-US": "Oxidized Copper"},
    {"zh-CN": "氧化的切制铜块", "en-US": "Oxidized Cut Copper"},
    {"zh-CN": "氧化的切制铜台阶", "en-US": "Oxidized Cut Copper Slab"},
    {"zh-CN": "氧化的切制铜楼梯", "en-US": "Oxidized Cut Copper Stairs"},
    {"zh-CN": "浮冰", "en-US": "Packed Ice"},
    {"zh-CN": "泥坯", "en-US": "Packed Mud"},
    {"zh-CN": "珠光蛙明灯", "en-US": "Pearlescent Froglight"},
    {"zh-CN": "牡丹", "en-US": "Peony"},
    {"zh-CN": "石化橡木台阶", "en-US": "Petrified Oak Slab"},
    {"zh-CN": "粉红色旗帜", "en-US": "Pink Banner"},
    {"zh-CN": "粉红色床", "en-US": "Pink Bed"},
    {"zh-CN": "粉红色蜡烛", "en-US": "Pink Candle"},
    {"zh-CN": "粉红色地毯", "en-US": "Pink Carpet"},
    {"zh-CN": "粉红色混凝土", "en-US": "Pink Concrete"},
    {"zh-CN": "粉红色混凝土粉末", "en-US": "Pink Concrete Powder"},
    {"zh-CN": "粉红色带釉陶瓦", "en-US": "Pink Glazed Terracotta"},
    {"zh-CN": "粉红色潜影盒", "en-US": "Pink Shulker Box"},
    {"zh-CN": "粉红色染色玻璃", "en-US": "Pink Stained Glass"},
    {"zh-CN": "粉红色染色玻璃板", "en-US": "Pink Stained Glass Pane"},
    {"zh-CN": "粉红色陶瓦", "en-US": "Pink Terracotta"},
    {"zh-CN": "粉红色郁金香", "en-US": "Pink Tulip"},
    {"zh-CN": "粉红色羊毛", "en-US": "Pink Wool"},
    {"zh-CN": "活塞", "en-US": "Piston"},
    {"zh-CN": "玩家的头", "en-US": "Player Head"},
    {"zh-CN": "灰化土", "en-US": "Podzol"},
    {"zh-CN": "滴水石锥", "en-US": "Pointed Dripstone"},
    {"zh-CN": "磨制安山岩", "en-US": "Polished Andesite"},
    {"zh-CN": "磨制安山岩台阶", "en-US": "Polished Andesite Slab"},
    {"zh-CN": "磨制安山岩楼梯", "en-US": "Polished Andesite Stairs"},
    {"zh-CN": "磨制玄武岩", "en-US": "Polished Basalt"},
    {"zh-CN": "磨制黑石", "en-US": "Polished Blackstone"},
    {"zh-CN": "磨制黑石砖台阶", "en-US": "Polished Blackstone Brick Slab"},
    {"zh-CN": "磨制黑石砖楼梯", "en-US": "Polished Blackstone Brick Stairs"},
    {"zh-CN": "磨制黑石砖墙", "en-US": "Polished Blackstone Brick Wall"},
    {"zh-CN": "磨制黑石砖", "en-US": "Polished Blackstone Bricks"},
    {"zh-CN": "磨制黑石按钮", "en-US": "Polished Blackstone Button"},
    {"zh-CN": "磨制黑石压力板", "en-US": "Polished Blackstone Pressure Plate"},
    {"zh-CN": "磨制黑石台阶", "en-US": "Polished Blackstone Slab"},
    {"zh-CN": "磨制黑石楼梯", "en-US": "Polished Blackstone Stairs"},
    {"zh-CN": "磨制黑石墙", "en-US": "Polished Blackstone Wall"},
    {"zh-CN": "磨制闪长岩", "en-US": "Polished Diorite"},
    {"zh-CN": "磨制闪长岩台阶", "en-US": "Polished Diorite Slab"},
    {"zh-CN": "磨制闪长岩楼梯", "en-US": "Polished Diorite Stairs"},
    {"zh-CN": "磨制花岗岩", "en-US": "Polished Granite"},
    {"zh-CN": "磨制花岗岩台阶", "en-US": "Polished Granite Slab"},
    {"zh-CN": "磨制花岗岩楼梯", "en-US": "Polished Granite Stairs"},
    {"zh-CN": "虞美人", "en-US": "Poppy"},
    {"zh-CN": "马铃薯", "en-US": "Potatoes"},
    {"zh-CN": "细雪", "en-US": "Powder Snow"},
    {"zh-CN": "动力铁轨", "en-US": "Powered Rail"},
    {"zh-CN": "海晶石", "en-US": "Prismarine"},
    {"zh-CN": "海晶石砖台阶", "en-US": "Prismarine Brick Slab"},
    {"zh-CN": "海晶石砖楼梯", "en-US": "Prismarine Brick Stairs"},
    {"zh-CN": "海晶石砖", "en-US": "Prismarine Bricks"},
    {"zh-CN": "海晶石台阶", "en-US": "Prismarine Slab"},
    {"zh-CN": "海晶石楼梯", "en-US": "Prismarine Stairs"},
    {"zh-CN": "海晶石墙", "en-US": "Prismarine Wall"},
    {"zh-CN": "南瓜", "en-US": "Pumpkin"},
    {"zh-CN": "南瓜茎", "en-US": "Pumpkin Stem"},
    {"zh-CN": "紫色旗帜", "en-US": "Purple Banner"},
    {"zh-CN": "紫色床", "en-US": "Purple Bed"},
    {"zh-CN": "紫色蜡烛", "en-US": "Purple Candle"},
    {"zh-CN": "紫色地毯", "en-US": "Purple Carpet"},
    {"zh-CN": "紫色混凝土", "en-US": "Purple Concrete"},
    {"zh-CN": "紫色混凝土粉末", "en-US": "Purple Concrete Powder"},
    {"zh-CN": "紫色带釉陶瓦", "en-US": "Purple Glazed Terracotta"},
    {"zh-CN": "紫色潜影盒", "en-US": "Purple Shulker Box"},
    {"zh-CN": "紫色染色玻璃", "en-US": "Purple Stained Glass"},
    {"zh-CN": "紫色染色玻璃板", "en-US": "Purple Stained Glass Pane"},
    {"zh-CN": "紫色陶瓦", "en-US": "Purple Terracotta"},
    {"zh-CN": "紫色羊毛", "en-US": "Purple Wool"},
    {"zh-CN": "紫珀块", "en-US": "Purpur Block"},
    {"zh-CN": "紫珀柱", "en-US": "Purpur Pillar"},
    {"zh-CN": "紫珀台阶", "en-US": "Purpur Slab"},
    {"zh-CN": "紫珀楼梯", "en-US": "Purpur Stairs"},
    {"zh-CN": "石英砖", "en-US": "Quartz Bricks"},
    {"zh-CN": "石英柱", "en-US": "Quartz Pillar"},
    {"zh-CN": "石英台阶", "en-US": "Quartz Slab"},
    {"zh-CN": "石英楼梯", "en-US": "Quartz Stairs"},
    {"zh-CN": "铁轨", "en-US": "Rail"},
    {"zh-CN": "红色旗帜", "en-US": "Red Banner"},
    {"zh-CN": "红色床", "en-US": "Red Bed"},
    {"zh-CN": "红色蜡烛", "en-US": "Red Candle"},
    {"zh-CN": "红色地毯", "en-US": "Red Carpet"},
    {"zh-CN": "红色混凝土", "en-US": "Red Concrete"},
    {"zh-CN": "红色混凝土粉末", "en-US": "Red Concrete Powder"},
    {"zh-CN": "红色带釉陶瓦", "en-US": "Red Glazed Terracotta"},
    {"zh-CN": "红色蘑菇", "en-US": "Red Mushroom"},
    {"zh-CN": "红色蘑菇方块", "en-US": "Red Mushroom Block"},
    {"zh-CN": "红色下界砖台阶", "en-US": "Red Nether Brick Slab"},
    {"zh-CN": "红色下界砖楼梯", "en-US": "Red Nether Brick Stairs"},
    {"zh-CN": "红色下界砖墙", "en-US": "Red Nether Brick Wall"},
    {"zh-CN": "红色下界砖块", "en-US": "Red Nether Bricks"},
    {"zh-CN": "红沙", "en-US": "Red Sand"},
    {"zh-CN": "红砂岩", "en-US": "Red Sandstone"},
    {"zh-CN": "红砂岩台阶", "en-US": "Red Sandstone Slab"},
    {"zh-CN": "红砂岩楼梯", "en-US": "Red Sandstone Stairs"},
    {"zh-CN": "红砂岩墙", "en-US": "Red Sandstone Wall"},
    {"zh-CN": "红色潜影盒", "en-US": "Red Shulker Box"},
    {"zh-CN": "红色染色玻璃", "en-US": "Red Stained Glass"},
    {"zh-CN": "红色染色玻璃板", "en-US": "Red Stained Glass Pane"},
    {"zh-CN": "红色陶瓦", "en-US": "Red Terracotta"},
    {"zh-CN": "红色郁金香", "en-US": "Red Tulip"},
    {"zh-CN": "红色羊毛", "en-US": "Red Wool"},
    {"zh-CN": "红石比较器", "en-US": "Redstone Comparator"},
    {"zh-CN": "红石灯", "en-US": "Redstone Lamp"},
    {"zh-CN": "红石矿石", "en-US": "Redstone Ore"},
    {"zh-CN": "红石中继器", "en-US": "Redstone Repeater"},
    {"zh-CN": "红石火把", "en-US": "Redstone Torch"},
    {"zh-CN": "红石粉", "en-US": "Redstone Wire"},
    {"zh-CN": "强化深板岩", "en-US": "Reinforced Deepslate"},
    {"zh-CN": "循环型命令方块", "en-US": "Repeating Command Block"},
    {"zh-CN": "重生锚", "en-US": "Respawn Anchor"},
    {"zh-CN": "缠根泥土", "en-US": "Rooted Dirt"},
    {"zh-CN": "玫瑰丛", "en-US": "Rose Bush"},
    {"zh-CN": "沙子", "en-US": "Sand"},
    {"zh-CN": "砂岩", "en-US": "Sandstone"},
    {"zh-CN": "砂岩台阶", "en-US": "Sandstone Slab"},
    {"zh-CN": "砂岩楼梯", "en-US": "Sandstone Stairs"},
    {"zh-CN": "砂岩墙", "en-US": "Sandstone Wall"},
    {"zh-CN": "脚手架", "en-US": "Scaffolding"},
    {"zh-CN": "幽匿块", "en-US": "Sculk"},
    {"zh-CN": "幽匿催发体", "en-US": "Sculk Catalyst"},
    {"zh-CN": "幽匿感测体", "en-US": "Sculk Sensor"},
    {"zh-CN": "幽匿尖啸体", "en-US": "Sculk Shrieker"},
    {"zh-CN": "幽匿脉络", "en-US": "Sculk Vein"},
    {"zh-CN": "海晶灯", "en-US": "Sea Lantern"},
    {"zh-CN": "海泡菜", "en-US": "Sea Pickle"},
    {"zh-CN": "海草", "en-US": "Seagrass"},
    {"zh-CN": "菌光体", "en-US": "Shroomlight"},
    {"zh-CN": "潜影盒", "en-US": "Shulker Box"},
    {"zh-CN": "骷髅头颅", "en-US": "Skeleton Skull"},
    {"zh-CN": "黏液块", "en-US": "Slime Block"},
    {"zh-CN": "小型紫晶芽", "en-US": "Small Amethyst Bud"},
    {"zh-CN": "小型垂滴叶", "en-US": "Small Dripleaf"},
    {"zh-CN": "锻造台", "en-US": "Smithing Table"},
    {"zh-CN": "烟熏炉", "en-US": "Smoker"},
    {"zh-CN": "平滑石英块", "en-US": "Smooth Quartz Block"},
    {"zh-CN": "平滑石英台阶", "en-US": "Smooth Quartz Slab"},
    {"zh-CN": "平滑石英楼梯", "en-US": "Smooth Quartz Stairs"},
    {"zh-CN": "平滑红砂岩", "en-US": "Smooth Red Sandstone"},
    {"zh-CN": "平滑红砂岩台阶", "en-US": "Smooth Red Sandstone Slab"},
    {"zh-CN": "平滑红砂岩楼梯", "en-US": "Smooth Red Sandstone Stairs"},
    {"zh-CN": "平滑砂岩", "en-US": "Smooth Sandstone"},
    {"zh-CN": "平滑砂岩台阶", "en-US": "Smooth Sandstone Slab"},
    {"zh-CN": "平滑砂岩楼梯", "en-US": "Smooth Sandstone Stairs"},
    {"zh-CN": "平滑石头", "en-US": "Smooth Stone"},
    {"zh-CN": "平滑石台阶", "en-US": "Smooth Stone Slab"},
    {"zh-CN": "雪", "en-US": "Snow"},
    {"zh-CN": "雪块", "en-US": "Snow Block"},
    {"zh-CN": "灵魂营火", "en-US": "Soul Campfire"},
    {"zh-CN": "灵魂火", "en-US": "Soul Fire"},
    {"zh-CN": "灵魂灯笼", "en-US": "Soul Lantern"},
    {"zh-CN": "灵魂火把", "en-US": "Soul Torch"},
    {"zh-CN": "灵魂沙", "en-US": "Soul Sand"},
    {"zh-CN": "灵魂土", "en-US": "Soul Soil"},
    {"zh-CN": "刷怪笼", "en-US": "Spawner"},
    {"zh-CN": "海绵", "en-US": "Sponge"},
    {"zh-CN": "孢子花", "en-US": "Spore Blossom"},
    {"zh-CN": "云杉木按钮", "en-US": "Spruce Button"},
    {"zh-CN": "云杉木门", "en-US": "Spruce Door"},
    {"zh-CN": "云杉木栅栏", "en-US": "Spruce Fence"},
    {"zh-CN": "云杉木栅栏门", "en-US": "Spruce Fence Gate"},
    {"zh-CN": "云杉树叶", "en-US": "Spruce Leaves"},
    {"zh-CN": "云杉原木", "en-US": "Spruce Log"},
    {"zh-CN": "云杉木板", "en-US": "Spruce Planks"},
    {"zh-CN": "云杉木压力板", "en-US": "Spruce Pressure Plate"},
    {"zh-CN": "云杉树苗", "en-US": "Spruce Sapling"},
    {"zh-CN": "云杉木告示牌", "en-US": "Spruce Sign"},
    {"zh-CN": "云杉木台阶", "en-US": "Spruce Slab"},
    {"zh-CN": "云杉木楼梯", "en-US": "Spruce Stairs"},
    {"zh-CN": "云杉木活板门", "en-US": "Spruce Trapdoor"},
    {"zh-CN": "云杉木", "en-US": "Spruce Wood"},
    {"zh-CN": "黏性活塞", "en-US": "Sticky Piston"},
    {"zh-CN": "石头", "en-US": "Stone"},
    {"zh-CN": "石砖台阶", "en-US": "Stone Brick Slab"},
    {"zh-CN": "石砖楼梯", "en-US": "Stone Brick Stairs"},
    {"zh-CN": "石砖墙", "en-US": "Stone Brick Wall"},
    {"zh-CN": "石砖", "en-US": "Stone Bricks"},
    {"zh-CN": "石质按钮", "en-US": "Stone Button"},
    {"zh-CN": "石质压力板", "en-US": "Stone Pressure Plate"},
    {"zh-CN": "石台阶", "en-US": "Stone Slab"},
    {"zh-CN": "石楼梯", "en-US": "Stone Stairs"},
    {"zh-CN": "切石机", "en-US": "Stonecutter"},
    {"zh-CN": "去皮金合欢原木", "en-US": "Stripped Acacia Log"},
    {"zh-CN": "去皮金合欢木", "en-US": "Stripped Acacia Wood"},
    {"zh-CN": "去皮白桦原木", "en-US": "Stripped Birch Log"},
    {"zh-CN": "去皮白桦木", "en-US": "Stripped Birch Wood"},
    {"zh-CN": "去皮绯红菌核", "en-US": "Stripped Crimson Hyphae"},
    {"zh-CN": "去皮绯红菌柄", "en-US": "Stripped Crimson Stem"},
    {"zh-CN": "去皮深色橡木原木", "en-US": "Stripped Dark Oak Log"},
    {"zh-CN": "去皮深色橡木", "en-US": "Stripped Dark Oak Wood"},
    {"zh-CN": "去皮丛林原木", "en-US": "Stripped Jungle Log"},
    {"zh-CN": "去皮丛林木", "en-US": "Stripped Jungle Wood"},
    {"zh-CN": "去皮红树原木", "en-US": "Stripped Mangrove Log"},
    {"zh-CN": "去皮红树木", "en-US": "Stripped Mangrove Wood"},
    {"zh-CN": "去皮橡木原木", "en-US": "Stripped Oak Log"},
    {"zh-CN": "去皮橡木", "en-US": "Stripped Oak Wood"},
    {"zh-CN": "去皮云杉原木", "en-US": "Stripped Spruce Log"},
    {"zh-CN": "去皮云杉木", "en-US": "Stripped Spruce Wood"},
    {"zh-CN": "去皮诡异菌核", "en-US": "Stripped Warped Hyphae"},
    {"zh-CN": "去皮诡异菌柄", "en-US": "Stripped Warped Stem"},
    {"zh-CN": "结构方块", "en-US": "Structure Block"},
    {"zh-CN": "结构空位", "en-US": "Structure Void"},
    {"zh-CN": "甘蔗", "en-US": "Sugar Cane"},
    {"zh-CN": "向日葵", "en-US": "Sunflower"},
    {"zh-CN": "甜浆果丛", "en-US": "Sweet Berry Bush"},
    {"zh-CN": "高草丛", "en-US": "Tall Grass"},
    {"zh-CN": "高海草", "en-US": "Tall Seagrass"},
    {"zh-CN": "陶瓦", "en-US": "Terracotta"},
    {"zh-CN": "遮光玻璃", "en-US": "Tinted Glass"},
    {"zh-CN": "TNT", "en-US": "TNT"},
    {"zh-CN": "火把", "en-US": "Torch"},
    {"zh-CN": "陷阱箱", "en-US": "Trapped Chest"},
    {"zh-CN": "绊线", "en-US": "Tripwire"},
    {"zh-CN": "绊线钩", "en-US": "Tripwire Hook"},
    {"zh-CN": "管珊瑚", "en-US": "Tube Coral"},
    {"zh-CN": "管珊瑚块", "en-US": "Tube Coral Block"},
    {"zh-CN": "管珊瑚扇", "en-US": "Tube Coral Fan"},
    {"zh-CN": "凝灰岩", "en-US": "Tuff"},
    {"zh-CN": "海龟蛋", "en-US": "Turtle Egg"},
    {"zh-CN": "缠怨藤", "en-US": "Twisting Vines"},
    {"zh-CN": "青翠蛙明灯", "en-US": "Verdant Froglight"},
    {"zh-CN": "藤蔓", "en-US": "Vines"},
    {"zh-CN": "诡异木按钮", "en-US": "Warped Button"},
    {"zh-CN": "诡异木门", "en-US": "Warped Door"},
    {"zh-CN": "诡异木栅栏", "en-US": "Warped Fence"},
    {"zh-CN": "诡异木栅栏门", "en-US": "Warped Fence Gate"},
    {"zh-CN": "诡异菌", "en-US": "Warped Fungus"},
    {"zh-CN": "诡异菌核", "en-US": "Warped Hyphae"},
    {"zh-CN": "诡异菌岩", "en-US": "Warped Nylium"},
    {"zh-CN": "诡异木板", "en-US": "Warped Planks"},
    {"zh-CN": "诡异木压力板", "en-US": "Warped Pressure Plate"},
    {"zh-CN": "诡异菌索", "en-US": "Warped Roots"},
    {"zh-CN": "诡异木告示牌", "en-US": "Warped Sign"},
    {"zh-CN": "诡异木台阶", "en-US": "Warped Slab"},
    {"zh-CN": "诡异木楼梯", "en-US": "Warped Stairs"},
    {"zh-CN": "诡异菌柄", "en-US": "Warped Stem"},
    {"zh-CN": "诡异木活板门", "en-US": "Warped Trapdoor"},
    {"zh-CN": "诡异疣块", "en-US": "Warped Wart Block"},
    {"zh-CN": "水", "en-US": "Water"},
    {"zh-CN": "涂蜡铜块", "en-US": "Waxed Block of Copper"},
    {"zh-CN": "涂蜡切制铜块", "en-US": "Waxed Cut Copper"},
    {"zh-CN": "涂蜡切制铜台阶", "en-US": "Waxed Cut Copper Slab"},
    {"zh-CN": "涂蜡切制铜楼梯", "en-US": "Waxed Cut Copper Stairs"},
    {"zh-CN": "斑驳的涂蜡铜块", "en-US": "Waxed Exposed Copper"},
    {"zh-CN": "斑驳的涂蜡切制铜块", "en-US": "Waxed Exposed Cut Copper"},
    {"zh-CN": "斑驳的涂蜡切制铜台阶", "en-US": "Waxed Exposed Cut Copper Slab"},
    {"zh-CN": "斑驳的涂蜡切制铜楼梯", "en-US": "Waxed Exposed Cut Copper Stairs"},
    {"zh-CN": "锈蚀的涂蜡铜块", "en-US": "Waxed Oxidized Copper"},
    {"zh-CN": "锈蚀的涂蜡切制铜块", "en-US": "Waxed Oxidized Cut Copper"},
    {"zh-CN": "锈蚀的涂蜡切制铜台阶", "en-US": "Waxed Oxidized Cut Copper Slab"},
    {"zh-CN": "锈蚀的涂蜡切制铜楼梯", "en-US": "Waxed Oxidized Cut Copper Stairs"},
    {"zh-CN": "氧化的涂蜡铜块", "en-US": "Waxed Weathered Copper"},
    {"zh-CN": "氧化的涂蜡切制铜块", "en-US": "Waxed Weathered Cut Copper"},
    {"zh-CN": "氧化的涂蜡切制铜台阶", "en-US": "Waxed Weathered Cut Copper Slab"},
    {"zh-CN": "氧化的涂蜡切制铜楼梯", "en-US": "Waxed Weathered Cut Copper Stairs"},
    {"zh-CN": "锈蚀的铜块", "en-US": "Weathered Copper"},
    {"zh-CN": "锈蚀的切制铜块", "en-US": "Weathered Cut Copper"},
    {"zh-CN": "锈蚀的切制铜台阶", "en-US": "Weathered Cut Copper Slab"},
    {"zh-CN": "锈蚀的切制铜楼梯", "en-US": "Weathered Cut Copper Stairs"},
    {"zh-CN": "垂泪藤", "en-US": "Weeping Vines"},
    {"zh-CN": "湿海绵", "en-US": "Wet Sponge"},
    {"zh-CN": "小麦", "en-US": "Wheat Crops"},
    {"zh-CN": "白色旗帜", "en-US": "White Banner"},
    {"zh-CN": "白色床", "en-US": "White Bed"},
    {"zh-CN": "白色蜡烛", "en-US": "White Candle"},
    {"zh-CN": "白色地毯", "en-US": "White Carpet"},
    {"zh-CN": "白色混凝土", "en-US": "White Concrete"},
    {"zh-CN": "白色混凝土粉末", "en-US": "White Concrete Powder"},
    {"zh-CN": "白色带釉陶瓦", "en-US": "White Glazed Terracotta"},
    {"zh-CN": "白色潜影盒", "en-US": "White Shulker Box"},
    {"zh-CN": "白色染色玻璃", "en-US": "White Stained Glass"},
    {"zh-CN": "白色染色玻璃板", "en-US": "White Stained Glass Pane"},
    {"zh-CN": "白色陶瓦", "en-US": "White Terracotta"},
    {"zh-CN": "白色郁金香", "en-US": "White Tulip"},
    {"zh-CN": "白色羊毛", "en-US": "White Wool"},
    {"zh-CN": "凋零玫瑰", "en-US": "Wither Rose"},
    {"zh-CN": "凋灵骷髅头颅", "en-US": "Wither Skeleton Skull"},
    {"zh-CN": "黄色旗帜", "en-US": "Yellow Banner"},
    {"zh-CN": "黄色床", "en-US": "Yellow Bed"},
    {"zh-CN": "黄色蜡烛", "en-US": "Yellow Candle"},
    {"zh-CN": "黄色地毯", "en-US": "Yellow Carpet"},
    {"zh-CN": "黄色混凝土", "en-US": "Yellow Concrete"},
    {"zh-CN": "黄色混凝土粉末", "en-US": "Yellow Concrete Powder"},
    {"zh-CN": "黄色带釉陶瓦", "en-US": "Yellow Glazed Terracotta"},
    {"zh-CN": "黄色潜影盒", "en-US": "Yellow Shulker Box"},
    {"zh-CN": "黄色染色玻璃", "en-US": "Yellow Stained Glass"},
    {"zh-CN": "黄色染色玻璃板", "en-US": "Yellow Stained Glass Pane"},
    {"zh-CN": "黄色陶瓦", "en-US": "Yellow Terracotta"},
    {"zh-CN": "黄色羊毛", "en-US": "Yellow Wool"},
    {"zh-CN": "僵尸的头", "en-US": "Zombie Head"}
  ]
}`